import { User, StudentProfile, CompanyProfile, Job, Application } from '@/types';

export const initialUsers: User[] = [
  {
    id: 'user-student-1',
    username: 'nhitran',
    email: 'nhitran@example.com',
    role: 'STUDENT',
    name: 'Trần Thị Yến Nhi',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-company-1',
    username: 'inuff',
    email: 'inuff@gmail.com',
    role: 'COMPANY',
    name: 'INUFF Technology',
    avatarUrl: '',
  },
];

export const initialStudentProfile: StudentProfile = {
  id: 'profile-student-1',
  userId: 'user-student-1',
  fullName: 'Trần Thị Yến Nhi',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  university: 'Trường Đại học Ngoại Thương',
  major: 'Kinh tế đối ngoại',
  expectedGraduationYear: 2028,
  gpa: 3.6,
  skills: ['Python', 'Web', 'Django', 'PostgreSQL', 'HTML/CSS', 'Git', 'Tiếng Anh giao tiếp'],
  goals: 'Mong muốn tìm kiếm cơ hội thực tập phát triển hệ thống và phân tích dữ liệu tại môi trường chuyên nghiệp.',
  cvFileName: 'CV_TranThiYenNhi_2026.pdf',
};

export const initialCompanyProfile: CompanyProfile = {
  id: 'profile-company-1',
  userId: 'user-company-1',
  companyName: 'INUFF',
  taxCode: '0109887766',
  industry: 'Công nghệ thông tin',
  companySize: '50–200 nhân viên',
  email: 'inuff@gmail.com',
  hotline: '0987654321',
  address: 'Số 12 Duy Tân, Cầu Giấy',
  city: 'Hà Nội',
  website: 'https://inuff.tech',
  description: 'Công ty công nghệ cung cấp giải pháp chuyển đổi số và phát triển phần mềm doanh nghiệp.',
};

export const initialJobs: Job[] = [
  {
    id: 'job-1',
    companyId: 'company-viettel',
    companyName: 'Viettel Digital',
    companyInitial: 'V',
    title: 'Data Analyst Intern (Phân tích Dữ liệu)',
    industry: 'Công nghệ thông tin',
    jobType: 'Thực tập Toàn thời gian',
    location: 'Hà Nội',
    minSalary: 3500000,
    maxSalary: 6000000,
    skills: ['SQL', 'Python', 'PowerBI'],
    description: 'Thu thập và làm sạch dữ liệu giao dịch tài chính số. Xây dựng dashboard báo cáo tự động cho ban điều hành.',
    requirements: 'Có kiến thức nền tảng về SQL và xử lý dữ liệu với Python. Thành thạo công cụ trực quan hóa PowerBI / Tableau là điểm cộng.',
    benefits: 'Trợ cấp hàng tháng từ 3.5 - 6.0 triệu VNĐ. Hỗ trợ dấu thực tập và mentor hướng dẫn 1-1 chuyên sâu.',
    isHot: true,
    isFeatured: true,
    quota: 3,
    createdAt: '2026-09-20',
  },
  {
    id: 'job-2',
    companyId: 'company-fpt',
    companyName: 'FPT Software',
    companyInitial: 'F',
    title: 'Thực tập sinh Python / Django Backend Developer',
    industry: 'Công nghệ thông tin',
    jobType: 'Thực tập Toàn thời gian',
    location: 'Cầu Giấy, Hà Nội',
    minSalary: 4000000,
    maxSalary: 7000000,
    skills: ['Python', 'Django', 'PostgreSQL'],
    description: 'Tham gia phát triển hệ thống backend quản lý dịch vụ đám mây bằng Django/Python. Xây dựng API chuẩn RESTful cho ứng dụng di động.',
    requirements: 'Nắm vững kiến thức lập trình hướng đối tượng với Python, cấu trúc dữ liệu và giải thuật. Có hiểu biết về relational DB (PostgreSQL, MySQL).',
    benefits: 'Môi trường làm việc quốc tế, cơ hội trở thành nhân viên chính thức sau 3 tháng thực tập. Trợ cấp 4 - 7 triệu/tháng.',
    isHot: true,
    isFeatured: true,
    quota: 5,
    createdAt: '2026-09-22',
  },
  {
    id: 'job-3',
    companyId: 'company-vng',
    companyName: 'VNG Corporation',
    companyInitial: 'V',
    title: 'Frontend Developer Intern (React / JavaScript)',
    industry: 'Công nghệ thông tin',
    jobType: 'Thực tập Toàn thời gian',
    location: 'Quận 7, TP. Hồ Chí Minh',
    minSalary: 5000000,
    maxSalary: 8000000,
    skills: ['JavaScript', 'React', 'HTML5'],
    description: 'Xây dựng giao diện các mini-app trên nền tảng di động và web portal. Tối ưu hiệu năng trải nghiệm người dùng tốc độ cao.',
    requirements: 'Thành thạo JavaScript (ES6+), HTML5, CSS3/Tailwind. Có kinh nghiệm làm dự án với React hoặc Next.js.',
    benefits: 'Trợ cấp hấp dẫn 5 - 8 triệu VNĐ/tháng, cơm trưa miễn phí tại canteen chuẩn 5 sao, máy tính cấu hình cao.',
    isHot: true,
    isFeatured: true,
    quota: 2,
    createdAt: '2026-09-23',
  },
  {
    id: 'job-4',
    companyId: 'company-fpt',
    companyName: 'FPT Software',
    companyInitial: 'F',
    title: 'Thực tập sinh DevOps & Cloud AWS',
    industry: 'Công nghệ thông tin',
    jobType: 'Thực tập Toàn thời gian',
    location: 'Hà Nội',
    minSalary: 4500000,
    maxSalary: 7500000,
    skills: ['Docker', 'AWS', 'Linux'],
    description: 'Tìm hiểu và vận hành hệ thống container với Docker và CI/CD pipeline trên nền tảng điện toán đám mây Amazon Web Services.',
    requirements: 'Yêu thích hệ thống Linux, mạng máy tính. Đã từng thực hành với Docker hoặc git flow.',
    benefits: 'Đào tạo chứng chỉ AWS quốc tế, lộ trình thăng tiến rõ ràng lên Junior Cloud Engineer.',
    isHot: false,
    isFeatured: false,
    quota: 3,
    createdAt: '2026-09-24',
  },
];

export const initialApplications: Application[] = [];
