// Fictional student profiles used by scripts/seed-applicants.mjs.
// Names and affiliations are invented. Avatars are Pexels workspace photos
// selected to show desks, laptops, architecture, or plants—not faces or people.

export const WORKSPACE_IMAGES = [
  'https://images.pexels.com/photos/1957478/pexels-photo-1957478.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  'https://images.pexels.com/photos/270360/pexels-photo-270360.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  'https://images.pexels.com/photos/380768/pexels-photo-380768.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  'https://images.pexels.com/photos/256541/pexels-photo-256541.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  'https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  'https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
];

export const applicants = [
  { slug: 'an-khoa-it', name: 'An Minh Khoa', focus: 'it', university: 'Đại học Công nghệ Bắc Minh', major: 'Khoa học Máy tính', graduationYear: 2027, gpa: 3.72, skills: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'Git'], goals: 'Hoàn thiện nền tảng phát triển backend và tích lũy kinh nghiệm làm việc nhóm trong môi trường sản phẩm.' },
  { slug: 'bia-linh-it', name: 'Bia Hoàng Linh', focus: 'it', university: 'Viện Đại học Khoa học Số Việt Nam', major: 'Kỹ thuật Phần mềm', graduationYear: 2026, gpa: 3.58, skills: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'Git'], goals: 'Phát triển API hiệu quả, viết kiểm thử tự động và cải thiện khả năng phân tích yêu cầu.' },
  { slug: 'chi-lan-it', name: 'Chi Ngọc Lan', focus: 'it', university: 'Trường Đại học Kỹ thuật Số Đông Dương', major: 'Hệ thống thông tin', graduationYear: 2027, gpa: 3.81, skills: ['C#', '.NET', 'SQL Server', 'REST API', 'Git'], goals: 'Mở rộng kiến thức về kiến trúc phân tán và xây dựng sản phẩm phần mềm bền vững.' },
  { slug: 'duy-an-it', name: 'Duy Đức An', focus: 'it', university: 'Đại học Công nghệ Thành Phố Mới', major: 'An toàn thông tin', graduationYear: 2026, gpa: 3.66, skills: ['Linux', 'Docker', 'CI/CD', 'Python', 'Git'], goals: 'Tăng cường năng lực vận hành hệ thống, tự động hóa triển khai và xử lý sự cố thực tế.' },
  { slug: 'giao-huyen-it', name: 'Giao Thị Huyền', focus: 'it', university: 'Đại học Dữ liệu và Trí tuệ Việt', major: 'Khoa học dữ liệu', graduationYear: 2027, gpa: 3.76, skills: ['SQL', 'Power BI', 'Python', 'ETL', 'Tableau'], goals: 'Biến dữ liệu thành thông tin dễ hiểu và đóng góp vào quyết định kinh doanh của doanh nghiệp.' },
  { slug: 'hai-an-it', name: 'Hải Đình An', focus: 'it', university: 'Trường Đại học Kỹ thuật Trọng Nghệ Sài Gòn', major: 'Công nghệ phần mềm', graduationYear: 2026, gpa: 3.49, skills: ['Java', 'Spring Boot', 'MySQL', 'REST API', 'Git'], goals: 'Nâng cao khả năng lập trình backend, hiểu kiến trúc dữ liệu và làm việc theo quy trình nhóm.' },
  { slug: 'hoa-my-it', name: 'Hoa Thị Mỹ', focus: 'it', university: 'Đại học Điện tử và Tin học Thành Phố Xanh', major: 'Công nghệ thông tin', graduationYear: 2027, gpa: 3.84, skills: ['JavaScript', 'Next.js', 'TypeScript', 'SQL', 'Git'], goals: 'Xây dựng giao diện và trải nghiệm sản phẩm tốt, đồng thời rèn luyện tư duy phân tích nghiệp vụ.' },
  { slug: 'khanh-vy-it', name: 'Khánh Vy', focus: 'it', university: 'Đại học Công nghệ Triều Minh', major: 'Trí tuệ nhân tạo', graduationYear: 2027, gpa: 3.69, skills: ['Python', 'PyTorch', 'SQL', 'Git', 'REST API'], goals: 'Ứng dụng mô hình học máy vào bài toán thực tế và hoàn thiện nền tảng kỹ thuật phần mềm.' },
  { slug: 'long-quang-it', name: 'Long Việt Quang', focus: 'it', university: 'Đại học Hệ thống Thông Minh', major: 'Kỹ thuật máy tính', graduationYear: 2026, gpa: 3.55, skills: ['C++', 'Linux', 'Docker', 'Git', 'SQL'], goals: 'Cải thiện năng lực lập trình hệ thống, hiểu sâu kiến trúc và tối ưu hiệu năng hệ thống.' },
  { slug: 'my-hanh-it', name: 'Mỹ Hạnh', focus: 'it', university: 'Đại học Số Phú Đông', major: 'Công nghệ phần mềm', graduationYear: 2027, gpa: 3.87, skills: ['TypeScript', 'React', 'Node.js', 'PostgreSQL', 'Git'], goals: 'Trở thành kỹ sư phần mềm có tư duy sản phẩm, giao tiếp rõ ràng và trách nhiệm cao.' },

  { slug: 'an-nhi-acc', name: 'An Thị Nhi', focus: 'accounting', university: 'Đại học Kế toán Á Châu', major: 'Kế toán', graduationYear: 2027, gpa: 3.78, skills: ['Excel', 'Kế toán', 'Kiểm soát nội bộ', 'Phần mềm kế toán', 'Phân tích tài chính'], goals: 'Rèn luyện kỹ năng đối chiếu số liệu, lập báo cáo và kiểm soát chứng từ theo quy định.' },
  { slug: 'binh-anh-acc', name: 'Bình Quốc Anh', focus: 'accounting', university: 'Viện Đại học Tài chính Đông Dương', major: 'Kiểm toán', graduationYear: 2026, gpa: 3.62, skills: ['Excel', 'Kiểm toán', 'Rủi ro kiểm soát', 'Phần mềm kế toán', 'Phân tích dữ liệu'], goals: 'Tích lũy kinh nghiệm kiểm toán và phát triển tư duy phát hiện rủi ro trong doanh nghiệp.' },
  { slug: 'cam-lan-acc', name: 'Cam Thị Lan', focus: 'accounting', university: 'Đại học Quản trị Kinh doanh Hoa Sen', major: 'Tài chính doanh nghiệp', graduationYear: 2027, gpa: 3.71, skills: ['Excel', 'Phân tích tài chính', 'Power BI', 'Kế toán', 'ERP'], goals: 'Phân tích số liệu tài chính và hỗ trợ ra quyết định quản trị bằng công cụ hiện đại.' },
  { slug: 'dieu-linh-acc', name: 'Diệu Linh', focus: 'accounting', university: 'Trường Đại học Kinh tế và Kế toán Việt Kiên', major: 'Kế toán công', graduationYear: 2026, gpa: 3.54, skills: ['Excel', 'Kế toán', 'Thuế', 'Phần mềm kế toán', 'Kiểm soát nội bộ'], goals: 'Nắm vững nghiệp vụ kế toán, thuế và vận hành phần mềm tại một môi trường doanh nghiệp.' },
  { slug: 'duc-thanh-acc', name: 'Đức Thành', focus: 'accounting', university: 'Đại học Tài chính Minh Hạnh', major: 'Kiểm toán', graduationYear: 2027, gpa: 3.66, skills: ['Excel', 'Kiểm toán', 'Phân tích tài chính', 'ERP', 'Power BI'], goals: 'Phát triển kỹ năng kiểm toán và sử dụng công nghệ để nâng cao chất lượng công việc.' },
  { slug: 'giao-duc-acc', name: 'Giao Quỳnh Đức', focus: 'accounting', university: 'Đại học Kinh tế Hồng Vân', major: 'Kế toán tài chính', graduationYear: 2026, gpa: 3.49, skills: ['Excel', 'Kế toán', 'Quản trị chi phí', 'ERP', 'Báo cáo tài chính'], goals: 'Hoàn thiện kỹ năng lập báo cáo, quản trị chi phí và hiểu sâu chu trình kế toán doanh nghiệp.' },
  { slug: 'hoang-anh-acc', name: 'Hoàng Quốc Anh', focus: 'accounting', university: 'Đại học Quản trị và Tài chính Sài Gòn', major: 'Tài chính', graduationYear: 2027, gpa: 3.75, skills: ['Excel', 'Phân tích tài chính', 'Mô hình tài chính', 'SQL', 'Power BI'], goals: 'Tăng cường năng lực phân tích đầu tư và sử dụng dữ liệu hỗ trợ quyết định tài chính.' },
  { slug: 'kim-ngan-acc', name: 'Kim Ngân', focus: 'accounting', university: 'Đại học Kế toán Tân Phát', major: 'Kế toán', graduationYear: 2026, gpa: 3.68, skills: ['Excel', 'Kế toán', 'Kiểm soát nội bộ', 'Phần mềm kế toán', 'Lập báo cáo'], goals: 'Xây dựng nền tảng chuẩn mực nghề và góp phần cải thiện chất lượng thông tin tài chính.' },
  { slug: 'linh-chi-acc', name: 'Linh Chi', focus: 'accounting', university: 'Đại học Kinh tế và Quản trị Đông Nam', major: 'Kiểm toán', graduationYear: 2027, gpa: 3.82, skills: ['Excel', 'Kiểm toán', 'Phân tích tài chính', 'ERP', 'Power Query'], goals: 'Nâng cao kỹ năng kiểm toán và tự động hóa quy trình đối chiếu, lập báo cáo.' },
  { slug: 'minh-quyen-acc', name: 'Minh Quyên', focus: 'accounting', university: 'Đại học Tài chính Thành Phố Vàng', major: 'Kế toán quản trị', graduationYear: 2026, gpa: 3.57, skills: ['Excel', 'Kế toán quản trị', 'Ngân sách', 'ERP', 'Phân tích tài chính'], goals: 'Ứng dụng kiến thức kế toán quản trị vào lập ngân sách, kiểm soát chi phí hiệu quả.' },

  { slug: 'an-chi-sales', name: 'An Thùy Chi', focus: 'sales', university: 'Trường Quản trị Kinh doanh Hồng Phát', major: 'Quản trị kinh doanh', graduationYear: 2027, gpa: 3.69, skills: ['Bán hàng', 'Tư vấn', 'CRM', 'Excel', 'Kỹ năng giao tiếp'], goals: 'Phát triển kỹ năng tư vấn, xây dựng quan hệ khách hàng và hiểu sâu vòng đời bán hàng.' },
  { slug: 'bao-cham-sales', name: 'Bảo Châm', focus: 'sales', university: 'Đại học Marketing và Bán hàng Việt Dương', major: 'Marketing', graduationYear: 2026, gpa: 3.58, skills: ['Bán hàng', 'CRM', 'Excel', 'Phân tích thị trường', 'Kỹ năng trình bày'], goals: 'Kết hợp dữ liệu để xây dựng phễu khách hàng và nâng cao hiệu quả bán hàng.' },
  { slug: 'cam-vy-sales', name: 'Cam Hoàng Vý', focus: 'sales', university: 'Đại học Thương mại và Dịch vụ Trẻ', major: 'Kinh doanh quốc tế', graduationYear: 2027, gpa: 3.77, skills: ['Bán hàng', 'CRM', 'Phân tích thị trường', 'Kỹ năng đàm phán', 'Tiếng Anh'], goals: 'Rèn năng lực đàm phán, chăm sóc khách hàng và phát triển cơ hội bán chéo sản phẩm.' },
  { slug: 'dat-nhat-sales', name: 'Đạt Nhật', focus: 'sales', university: 'Viện Đại học Kinh doanh Đức Hành', major: 'Quản trị kinh doanh', graduationYear: 2026, gpa: 3.53, skills: ['Bán hàng', 'CRM', 'Excel', 'Quản lý khách hàng', 'Kỹ năng trình bày'], goals: 'Xây dựng nền tảng bán hàng có hệ thống và phát triển kỹ năng quản lý đội nhóm.' },
  { slug: 'diem-quyen-sales', name: 'Diễm Quyên', focus: 'sales', university: 'Đại học Kinh tế và Quản trị Bình Minh', major: 'Marketing', graduationYear: 2027, gpa: 3.73, skills: ['CRM', 'Excel', 'SEO', 'Phân tích thị trường', 'Kỹ năng trình bày'], goals: 'Kết hợp kiến thức marketing và kinh doanh để tăng tốc phát triển doanh thu bền vững.' },
  { slug: 'gia-bao-sales', name: 'Gia Bảo', focus: 'sales', university: 'Đại học Bán hàng và Thị trường Nhân Phát', major: 'Kinh doanh', graduationYear: 2026, gpa: 3.47, skills: ['Bán hàng', 'CRM', 'Excel', 'Kỹ năng đàm phán', 'Quản lý khách hàng'], goals: 'Tích lũy kinh nghiệm phát triển khách hàng, chốt đơn và chăm sóc khách hàng sau bán.' },
  { slug: 'hoang-nhung-sales', name: 'Hoàng Thị Nhung', focus: 'sales', university: 'Đại học Thương mại Quốc tế Đại Việt', major: 'Kinh doanh quốc tế', graduationYear: 2027, gpa: 3.79, skills: ['Bán hàng', 'CRM', 'Kỹ năng đàm phán', 'Tiếng Anh', 'Excel'], goals: 'Mở rộng năng lực kinh doanh xuyên kênh và chuẩn bị cho môi trường làm việc quốc tế.' },
  { slug: 'kim-linh-sales', name: 'Kim Linh', focus: 'sales', university: 'Đại học Kinh tế và Bán hàng Thanh Bình', major: 'Quản trị kinh doanh', graduationYear: 2026, gpa: 3.61, skills: ['CRM', 'Excel', 'Chăm sóc khách hàng', 'Bán hàng', 'Kỹ năng trình bày'], goals: 'Phát triển kỹ năng phân tích khách hàng và duy trì mối quan hệ lâu dài với đối tác.' },
  { slug: 'minh-khang-sales', name: 'Minh Khang', focus: 'sales', university: 'Đại học Quản trị Đại Dương', major: 'Logistics', graduationYear: 2027, gpa: 3.65, skills: ['Bán hàng', 'CRM', 'Excel', 'Logistics', 'Kỹ năng đàm phán'], goals: 'Kết hợp kiến thức logistics với kỹ năng chốt đơn để tối ưu vận hành và doanh thu.' },
  { slug: 'nhu-yen-sales', name: 'Như Yên', focus: 'sales', university: 'Đại học Bán hàng Quốc tế Ánh Dương', major: 'Kinh doanh quốc tế', graduationYear: 2026, gpa: 3.7, skills: ['CRM', 'Kỹ năng đàm phán', 'Tiếng Anh', 'Phân tích thị trường', 'Bán hàng'], goals: 'Trở thành chuyên viên phát triển thị trường với tư duy dữ liệu và kỹ năng giao tiếp vượt trội.' },
];
